import { z } from "zod";

export const PrInsightArtifactSchema = z.object({
  kind: z.enum(["insight_preview", "review_run"]),
  at: z.string().optional(),
  repository: z.string().default(""),
  pullRequestId: z.coerce.number().int().nonnegative(),
  title: z.string().default(""),
  summary: z.string().default(""),
  readiness: z.enum(["ready", "needs_attention", "blocked"]).optional(),
  decisionQueue: z.enum(["auto_approved", "needs_human_review", "blocked", "watching"]).optional(),
  decisionRiskLevel: z.enum(["low", "medium", "high"]).optional(),
  contextConfidence: z.enum(["high", "medium", "low", ""]).optional(),
  risks: z.array(z.string()).default([]),
  categories: z.object({
    blocking: z.array(z.string()).default([]),
    warnings: z.array(z.string()).default([]),
    info: z.array(z.string()).default([]),
  }).optional(),
  signals: z.object({
    fileCount: z.coerce.number().int().nonnegative().default(0),
    threadCount: z.coerce.number().int().nonnegative().default(0),
    failedBuildCount: z.coerce.number().int().nonnegative().default(0),
    workItemCount: z.coerce.number().int().nonnegative().default(0),
    failedPolicyCount: z.coerce.number().int().nonnegative().optional(),
    buildBlockers: z.array(z.object({
      id: z.coerce.number().int().nonnegative().default(0),
      buildNumber: z.string().default(""),
      definitionName: z.string().default(""),
      status: z.string().default(""),
      result: z.string().default(""),
      url: z.string().default(""),
    })).optional(),
    policyBlockers: z.array(z.object({
      id: z.string().default(""),
      name: z.string().default(""),
      typeName: z.string().default(""),
      status: z.string().default(""),
      isBlocking: z.boolean().default(false),
    })).optional(),
    activeThreads: z.array(z.object({
      id: z.coerce.number().int().nonnegative().default(0),
      status: z.union([z.string(), z.number()]).default(""),
      author: z.string().default(""),
      firstComment: z.string().default(""),
    })).optional(),
    linkedWorkItems: z.array(z.object({
      id: z.coerce.number().int().nonnegative().default(0),
      type: z.string().default(""),
      title: z.string().default(""),
      state: z.string().default(""),
      url: z.string().default(""),
    })).optional(),
  }).optional(),
  iterationId: z.coerce.number().int().nonnegative().optional(),
  sourceCommit: z.string().optional(),
  findingCount: z.coerce.number().int().nonnegative().optional(),
  discardedFindingCount: z.coerce.number().int().nonnegative().optional(),
  tokensIn: z.coerce.number().int().nonnegative().default(0),
  tokensOut: z.coerce.number().int().nonnegative().default(0),
});
