import { z } from "zod";

export const ReviewHistoryUpsertSchema = z.object({
  pullRequestId: z.coerce.number().int().positive(),
  lastIterationId: z.coerce.number().int().nonnegative().default(0),
  findingCount: z.coerce.number().int().nonnegative().default(0),
  lastRunAt: z.string().default(() => new Date().toISOString()),
  sourceCommit: z.string().default(""),
  decisionQueue: z.enum(["auto_approved", "needs_human_review", "blocked", "watching"]).default("needs_human_review"),
  decisionRiskLevel: z.enum(["low", "medium", "high"]).default("medium"),
  decisionReason: z.string().default(""),
  decisionReasonCodes: z.array(z.string()).default([]),
  contextConfidence: z.enum(["high", "medium", "low", ""]).default(""),
  autoApprovedAt: z.string().default(""),
  autoApprovalActor: z.string().default(""),
  lastTokensIn: z.coerce.number().int().nonnegative().optional(),
  lastTokensOut: z.coerce.number().int().nonnegative().optional(),
  discardedFindingCount: z.coerce.number().int().nonnegative().optional(),
  hunkCoverageFiles: z.coerce.number().int().nonnegative().optional(),
  wholeFileFallbackFiles: z.coerce.number().int().nonnegative().optional(),
  changedHunkLines: z.coerce.number().int().nonnegative().optional(),
  manualDisposition: z.enum(["", "acknowledged", "marked_safe", "marked_blocked", "changes_requested"]).default(""),
  manualDispositionAt: z.string().default(""),
  manualDispositionActor: z.string().default(""),
  manualDispositionNote: z.string().default(""),
  manualDispositionEvents: z.array(z.object({
    disposition: z.enum(["acknowledged", "marked_safe", "marked_blocked", "changes_requested"]),
    at: z.string().default(""),
    actor: z.string().default(""),
    note: z.string().default(""),
  })).default([]),
  manualDispositionWriteBackAttempted: z.boolean().default(false),
  manualDispositionWriteBackOk: z.boolean().default(false),
  manualDispositionWriteBackError: z.string().default(""),
  manualDispositionWriteBackAt: z.string().default(""),
  manualDispositionWriteBackThreadId: z.string().default(""),
  manualDispositionWriteBackUrl: z.string().default(""),
  manualDispositionWriteBackEvents: z.array(z.object({
    disposition: z.enum(["acknowledged", "marked_safe", "marked_blocked", "changes_requested"]),
    at: z.string().default(""),
    ok: z.boolean().default(false),
    actor: z.string().default(""),
    note: z.string().default(""),
    error: z.string().default(""),
    threadId: z.string().default(""),
    url: z.string().default(""),
  })).default([]),
});
export type ReviewHistoryUpsert = z.infer<typeof ReviewHistoryUpsertSchema>;

export const ReviewDispositionUpsertSchema = ReviewHistoryUpsertSchema.extend({
  writeBackToAdo: z.boolean().default(true),
});
export type ReviewDispositionUpsert = z.infer<typeof ReviewDispositionUpsertSchema>;

export const ReviewOperationSchema = z.object({
  kind: z.enum(["rerun", "batch_rerun", "stale_rerun", "disposition", "ado_retry", "insight_preview", "review_run"]),
  at: z.string().optional(),
  pullRequestId: z.coerce.number().int().nonnegative().default(0),
  actor: z.string().default("desktop-user"),
  label: z.string().default(""),
  ok: z.boolean().default(true),
  details: z.string().default(""),
});

export const PrInsightArtifactSchema = z.object({
  kind: z.enum(["insight_preview", "review_run"]),
  at: z.string().optional(),
  repository: z.string().default(""),
  pullRequestId: z.coerce.number().int().nonnegative(),
  title: z.string().default(""),
  summary: z.string().default(""),
  readiness: z.enum(["ready", "needs_attention", "blocked"]).optional(),
  decisionQueue: z.enum(["auto_approved", "needs_human_review", "blocked", "watching"]).optional(),
  decisionRiskLevel: z.enum(["low", "medium", "high"]).optional(),
  contextConfidence: z.enum(["high", "medium", "low", ""]).optional(),
  risks: z.array(z.string()).default([]),
  categories: z.object({
    blocking: z.array(z.string()).default([]),
    warnings: z.array(z.string()).default([]),
    info: z.array(z.string()).default([]),
  }).optional(),
  signals: z.object({
    fileCount: z.coerce.number().int().nonnegative().default(0),
    threadCount: z.coerce.number().int().nonnegative().default(0),
    failedBuildCount: z.coerce.number().int().nonnegative().default(0),
    workItemCount: z.coerce.number().int().nonnegative().default(0),
    failedPolicyCount: z.coerce.number().int().nonnegative().optional(),
    buildBlockers: z.array(z.object({
      id: z.coerce.number().int().nonnegative().default(0),
      buildNumber: z.string().default(""),
      definitionName: z.string().default(""),
      status: z.string().default(""),
      result: z.string().default(""),
      url: z.string().default(""),
    })).optional(),
    policyBlockers: z.array(z.object({
      id: z.string().default(""),
      name: z.string().default(""),
      typeName: z.string().default(""),
      status: z.string().default(""),
      isBlocking: z.boolean().default(false),
    })).optional(),
    activeThreads: z.array(z.object({
      id: z.coerce.number().int().nonnegative().default(0),
      status: z.union([z.string(), z.number()]).default(""),
      author: z.string().default(""),
      firstComment: z.string().default(""),
    })).optional(),
    linkedWorkItems: z.array(z.object({
      id: z.coerce.number().int().nonnegative().default(0),
      type: z.string().default(""),
      title: z.string().default(""),
      state: z.string().default(""),
      url: z.string().default(""),
    })).optional(),
  }).optional(),
  iterationId: z.coerce.number().int().nonnegative().optional(),
  sourceCommit: z.string().optional(),
  findingCount: z.coerce.number().int().nonnegative().optional(),
  discardedFindingCount: z.coerce.number().int().nonnegative().optional(),
  tokensIn: z.coerce.number().int().nonnegative().default(0),
  tokensOut: z.coerce.number().int().nonnegative().default(0),
});
